language: smalltalk
sudo: false

os:
- linux
#- osx
#- windows

smalltalk:
  - Pharo64-8.0
  # - Pharo64-9.0

# https://docs.travis-ci.com/user/build-matrix/
# matrix:
#   fast_finish: true
#   allow_failures:
#     - smalltalk: Pharo64-8.0 Pharo64-9.0

services:
  - mongodb

before_script:
  - mongo test --eval 'db.createUser({user:"pharounittest",pwd:"test",roles:[]});'

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - cp "${SMALLTALK_CI_IMAGE}" "PharoWeb.image"
  - cp "${SMALLTALK_CI_CHANGES}" "PharoWeb.changes"
  - PHARO_VERSION=`echo ${TRAVIS_SMALLTALK_VERSION} | awk -F- '{print $2;}'`
  - RESULT_ZIP="PharoWeb-${PHARO_VERSION}.zip"
  - zip ${RESULT_ZIP} "PharoWeb.image" "PharoWeb.changes"
  - bash upload.sh ${RESULT_ZIP}

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure:
  file: "PharoWeb*.zip"
  on:
    repo: LucFabresse/PharoWeb
    tags: true
  draft: true