language: smalltalk
sudo: false

os:
- linux
#- osx
#- windows

smalltalk:
  - Pharo64-8.0
  # - Pharo64-9.0

# matrix:
#   fast_finish: true
#   allow_failures:
#     - smalltalk: Pharo64-8.0 Pharo64-9.0

services:
  - mongodb

before_install:
  - "scripts/downloadAndCachePharoImage.sh"

before_script:
  - mongo test --eval 'db.createUser({user:"pharounittest",pwd:"test",roles:[]});'

script:
  - smalltalkci .null.ston

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - cp "${SMALLTALK_CI_IMAGE}" "PharoWeb.image"
  - cp "${SMALLTALK_CI_CHANGES}" "PharoWeb.changes"
  - cp "${SMALLTALK_CI_BUILD}/*.sources" .
  - PHARO_VERSION=`echo ${TRAVIS_SMALLTALK_VERSION} | awk -F- '{print $2;}'`
  - RESULT_ZIP="PharoWeb-${PHARO_VERSION}.zip"
  - zip ${RESULT_ZIP} "PharoWeb.image" "PharoWeb.changes" "*.sources"
  - bash upload.sh ${RESULT_ZIP}

branches:
  except:
    - /^(?i:continuous.*)$/

# deploy:
#   skip_cleanup: true
#   provider: releases
#   api_key:
#     secure: KqDq6UnHmEY9WL6AqPo/5ZeIxB24lnBygZrVZjRZjPaqmvIe2NdfHmzn1kqphf22FtkEIJCjiI6A5AKGAA4XD8c3nb5IgWOIPluGlEZEaGeYdd6ni6EXzc940DaSM4+SKk1akInR8fOEnGD3odrICUKhS0yNnni3eeDohPm9gyBEocCA3aPIvlXdxAdjhDKTIB7mEqEtB8ietr5kL+GLvCF+awISQSUEyB7wf05YO/eb0OJ9hPzwAab++tJ+vVy+Dp3pJ8ICpkM0F42pFTzv6HLoJDmbVqX3nCCtjEzZPJohhMdmIJSqqPeqH6BIs9Ut2xZkqbKRwbFJJwidRRil7MVJhtKlEOukCctryVwpyX5UBWDHqWSLSiXQ8mCadRTS3cit2nzr2udtu5Kpxkn+fN+WgC5VuORaktpn1/HzLgsrECt9P619jVxoN6JDdUlKX40WhJ/lj8CoUZA08ag8v7z3mfaJZlLGYWwQthgdsGvOFbGJdDZ0zTq5f5L++G8an4UXfcT9iA/3l0no8JshTF2DtHhfyslx9vgOyGmBof0WZqEg0t52aAfg6MIv0sKB/Qb7yux/rqiP5OfayWa7Iv1oqEA6Ymn4FqvyDM67HT1Adsr0UpB/AaaE7bQXRndUy8G242w2U4cLY0FmH5QxZ6CX+mzOW0yhU5QXtL5OYVQ==
#   file_glob: true
#   file: "PharoWeb*.zip"
#   on:
#     repo: LucFabresse/PharoWeb
#     tags: true
#   # draft: true
